goyervideoblog/urls.py
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
admin.autodiscover()


urlpatterns = staticfiles_urlpatterns() \
    + [
        url(r'^admin/', include(admin.site.urls)),
        url(r'^lucas/', include('lucas.urls', namespace='lucas')),
        url(r'^', include('posts.urls', namespace='posts')),

    ]

lucas/urls.py
from django.conf.urls import url

from .views import LucasListView, LucasDetailView

urlpatterns = [
    url(r'(?P<pk>\d+)/$', LucasDetailView.as_view(), name='detail'),
    url(r'$', LucasListView.as_view(), name='list'),
]

posts/urls.py
from django.conf.urls import url

from .views import PostListView, PostDetailView

urlpatterns = [
    url(r'(?P<pk>\d+)/$', PostDetailView.as_view(), name='detail'),
    url(r'$', PostListView.as_view(), name='list'),
]

lucas/models.py
from django.db import models
from django.core.urlresolvers import reverse

from embed_video.fields import EmbedVideoField


class Lucas(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=300)
    video = EmbedVideoField(verbose_name='My video',
                            help_text='This is a help text')

    def __unicode__(self):
        return self.title


    def __unicode__(self):
        return self.description

    def get_absolute_url(self):
        return reverse('lucas:detail', kwargs={'pk': self.pk})

posts/models.py
from django.db import models
from django.core.urlresolvers import reverse

from embed_video.fields import EmbedVideoField


class Post(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(max_length=3000)
    pub_date = models.DateTimeField()
    video = EmbedVideoField(verbose_name='My video',
                            help_text='This is a help text')

    def __unicode__(self):
        return self.title


    def __unicode__(self):
        return self.description

    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'pk': self.pk})

    def pub_date_pretty(self):
        return self.pub_date.strftime('%b %e %Y')

lucas/views.py
from django.views.generic import ListView, DetailView

from .models import Lucas


class LucasListView(ListView):
    model = Lucas
    paginate_by = 10


class LucasDetailView(DetailView):
    model = Lucas

posts/views.py
from django.views.generic import ListView, DetailView

from .models import Post


class PostListView(ListView):
    model = Post
    paginate_by = 10

    def get_queryset(self):
        queryset = Post.objects.order_by('-pub_date')
        return queryset

class PostDetailView(DetailView):
    model = Post

embed_video/templates/embed_video/embed_code.html
<iframe width="{{ width }}" height="{{ height }}" src="{{ backend.url }}" frameborder="0" allowfullscreen></iframe>

goyervideoblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Goyer's Blog</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style>


    .detail {
  line-height: 0;
  font-size: 0;
}

/* Sets the font and line height correctly for the paragraph of text */
.detail {
  line-height: 16px;
  font-size: 16px;
}
    body {
      font-size: 32px;
    }

    h1 {
      font-size: 64px;
      margin: 20px 5px;
    }
    </style>

</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynav">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'posts:list' %}">Goyer's Blog</a>
        </div>
        <div class="btn-group">


            <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Techniques <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'lucas:list' %}">Lucas Lepri</a></li>
                    <li><a href="#">Rafael Lovato Jr.</a></li>
                    <li><a href="#">Stephan Kesting</a></li>
                    <li><a href="#"></a></li>
                </ul>
            </div>

            <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Rolling <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li><a href="#">Separated link</a></li>
                </ul>
            </div>

            <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Competition <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li><a href="#">Separated link</a></li>
                </ul>
            </div>

        </div>
    </div>
</nav>

<div class="container">

    {% block content %}{% endblock %}

</div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

lucas/templates/lucas/lucas_detail.html
{% extends "base.html" %}

{% load embed_video_tags %}

{% block content %}

<h1>
  {{ object.title }}
  <a href="{% url "lucas:list" %}" class="pull-right"><small>Back to list</small></a>
</h1>

{% video object.video as my_video %}


  {% video my_video "large" %}
{% endvideo %}

{% endblock %}

lucas/templates/lucas/lucas_list.html
{% extends "base.html" %}

{% load embed_video_tags %}

{% block content %}

<h1>Lucas Lepri</h1>
  <table class="table">
    {% for lucas in object_list %}
    <tr>
      {% video lucas.video as video %}
        <td class = detail> <pre>{{ lucas.title }}</pre>
      {{ lucas.description }} </td>
      <td><a href="{{ lucas.get_absolute_url }}"><img src="{{ video.thumbnail }}" width=240 height=190 class="img-rounded"></a></td>
      {% endvideo %}
    </tr>

    {% endfor %}
  </table>

  <ul class="pager">
    {% if page_obj.has_previous %}
    <li class="previous"><a href="?page={{ page_obj.previous_page_number }}">&larr; Older</a></li>
    {% endif %}
    {% if page_obj.has_next %}
      <li class="next"><a href="?page={{ page_obj.next_page_number }}">Newer &rarr;</a></li>
    {% endif %}
  </ul>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends "base.html" %}

{% load embed_video_tags %}

{% block content %}

<h1>
  {{ object.title }}
  <a href="{% url "posts:list" %}" class="pull-right"><small>Back to list</small></a>
</h1>

{% video object.video as my_video %}
  

  {% video my_video "large" %}
{% endvideo %}

{% endblock %}

posts/templates/posts/post_list.html
{% extends "base.html" %}

{% load embed_video_tags %}

{% block content %}



<h1>BJJ Journal Posts</h1>
  <table class="table">
    {% for post in object_list %}
    <tr>
      {% video post.video as video %}
        <td><font size="4"><pre>{{ post.pub_date_pretty }}</pre> </font> </td>
      <td class="detail"><font size="4">{{ post.description }} </font></td>
      <td><a href="{{ post.get_absolute_url }}"><img src="{{ video.thumbnail }}" width=240 height=180 class="img-rounded"></a></td>
      {% endvideo %}
    </tr>

    {% endfor %}
  </table>

  <ul class="pager">
    {% if page_obj.has_previous %}
    <li class="previous"><a href="?page={{ page_obj.previous_page_number }}">&larr; Older</a></li>
    {% endif %}
    {% if page_obj.has_next %}
      <li class="next"><a href="?page={{ page_obj.next_page_number }}">Newer &rarr;</a></li>
    {% endif %}
  </ul>
{% endblock %}